= 关联组件设计文档
xiayx <xiayouxue@hotmail.com>
v1.0, 2018-04-29: SNAPSHOT
:doctype: docbook
:toc: left
:numbered:
:imagesdir: assets/images
:sourcedir: src/main/java
:resourcesdir: src/main/resources
:testsourcedir: src/test/java
:source-highlighter: highlightjs

用于设置实体对象的关联值。

=== 单一关联对象
开发过程中遇到如下场景：一个"主实体类"通过一个"关联主键"关联一个"关联实体类"，
数据库中记录着"关联主键"的值，实际使用时需要通过"关联主键"取得"关联对象"。

.关联实体类（省略getter/setter）
[source%nowrap,java]
----
include::{testsourcedir}/org/freedom/associate/Associate.java[tags=entity]
----

.主实体类（省略getter/setter）
[source%nowrap,java]
----
include::{testsourcedir}/org/freedom/associate/Main.java[tags=associateId;class]
----
<1> 关联主键
<2> 关联对象


从数据库查出``Main``对象时，``associateId``有值，但``associate``无值，
此时需要通过``associateId``为``associate``赋值，
实现这个过程需要以下三个步骤：

. 从主实体对象中取出关联主键
. 通过关联主键取得关联对象
. 将关联对象设置回主实体对象

步骤1和步骤3可通过属性反射实现，
步骤2需要通过一个接口实现，此接口提供一个通过关联主键获取关联对象的方法，暂且命名为"关联对象源"。
通用调用代码可能型似``setAssociate(主对象,关联属性,关联对象源,关联属性主键)``

== 集合关联对象
上面介绍的关联对象为单一形式，但它也可以是集合形式，如下所示：

.主实体类（省略getter/setter）
[source%nowrap,java]
----
include::{testsourcedir}/org/freedom/associate/Main.java[tags=associateIds;class]
----
<1> 关联主键集合
<2> 关联对象集合

步骤2还需要另一个接口，此接口提供一个通过关联主键集合获取关联对象集合的方法，暂且命名为"集合关联对象源"。
通用调用代码可能型似``setAssociate(主对象,关联属性,集合关联对象源,关联属性主键)``

== 集合主对象
上面所说的都是为单一主对象设置关联对象，实际上也需要为集合主对象设置关联对象。
可以简单的在循环中套用上面的实现，但是如果关联对象源每次都去数据库查询关联对象，
循环会导致连库次数过多，而实际上只需要一次查询，那么如何使用一次查询呢？

* 从集合主对象MS中取出集合关联主键AIS
* 通过集合关联主键AIS取出集合关联对象AS
* 将集合关联对象AS转换成主键到对象的映射AM
* 为每一个主对象M设置关联属性
** 从主对象M中取出关联主键AI
** 从AM中取出关联主键AI对应的关联对象A
** 将关联对象A设置回主对象M

== 设置关联属性
上面所说的都是为主对象设置关联对象，也可以为主对象设置关联属性，如下所示：

.主实体类（省略getter/setter）
[source%nowrap,java]
----
include::{testsourcedir}/org/freedom/associate/Main.java[tags=class;associateId;associateName]
----


=== 实现
* AssociateUtils：工具类提供通用的设置方法，设置方法一共8个（主实体对象表现形式[2]*关联对象表现形式[2]*关联对象取得方式[2]=8）
** setAssociate：关联对象为单一对象的情况
** setCollectionAssociate：关联对象为集合对象的情况
* AssociateSource：关联对象源，用于提供单一关联对象
* CollectionAssociateSource：集合关联对象源，用于提供集合关联对象


=== 待完善
* AssociateService，提供更加简单易用的接口
** 根据关联对象属性推测关联主键属性
** 设置默认的主键属性


